<a href="https://colab.research.google.com/github/rakshithasetty41/statistics/blob/main/auto_regression_25_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
tmpr = [10, 12, 13, 14.5, 16, 17, 17.9, 18, 21, 22, 21, 20, 18.7, 18, 16.8, 16, 15.4, 15.1]
len(tmpr)

18

In [ ]:
# 18 days of temperature recorded.based on given time line of data,estimate tomorrow's (19th day ) temperature.


In [ ]:
past=tmpr[:-1]
present=tmpr[1:]
list(zip(past,present))

[(10, 12),
 (12, 13),
 (13, 14.5),
 (14.5, 16),
 (16, 17),
 (17, 17.9),
 (17.9, 18),
 (18, 21),
 (21, 22),
 (22, 21),
 (21, 20),
 (20, 18.7),
 (18.7, 18),
 (18, 16.8),
 (16.8, 16),
 (16, 15.4),
 (15.4, 15.1)]

In [ ]:
import numpy as np

In [ ]:
ones=np.ones(len(past))
len(ones)

17

In [ ]:
X=np.c_[ones,past]
X.shape

(17, 2)

In [ ]:
X

array([[ 1. , 10. ],
       [ 1. , 12. ],
       [ 1. , 13. ],
       [ 1. , 14.5],
       [ 1. , 16. ],
       [ 1. , 17. ],
       [ 1. , 17.9],
       [ 1. , 18. ],
       [ 1. , 21. ],
       [ 1. , 22. ],
       [ 1. , 21. ],
       [ 1. , 20. ],
       [ 1. , 18.7],
       [ 1. , 18. ],
       [ 1. , 16.8],
       [ 1. , 16. ],
       [ 1. , 15.4]])

In [ ]:
Y=np.c_[present]
Y.shape

(17, 1)

In [ ]:
Y

array([[12. ],
       [13. ],
       [14.5],
       [16. ],
       [17. ],
       [17.9],
       [18. ],
       [21. ],
       [22. ],
       [21. ],
       [20. ],
       [18.7],
       [18. ],
       [16.8],
       [16. ],
       [15.4],
       [15.1]])

In [ ]:
np.corrcoef(past,present)

array([[1.        , 0.92227187],
       [0.92227187, 1.        ]])

In [ ]:
def weights(x,y):
  from numpy.linalg import inv
  l=inv(x.T.dot(x))
  r=x.T.dot(y)
  return l.dot(r)


In [ ]:
w=weights(X,Y)
w.shape

(2, 1)

In [ ]:
w

array([[3.84901961],
       [0.78999884]])

In [ ]:
ycap=X.dot(w)
ycap

array([[11.74900801],
       [13.32900569],
       [14.11900452],
       [15.30400278],
       [16.48900104],
       [17.27899988],
       [17.98999884],
       [18.06899872],
       [20.43899524],
       [21.22899408],
       [20.43899524],
       [19.6489964 ],
       [18.62199791],
       [18.06899872],
       [17.12100012],
       [16.48900104],
       [16.01500174]])

In [ ]:
np.c_[Y,ycap]

array([[12.        , 11.74900801],
       [13.        , 13.32900569],
       [14.5       , 14.11900452],
       [16.        , 15.30400278],
       [17.        , 16.48900104],
       [17.9       , 17.27899988],
       [18.        , 17.98999884],
       [21.        , 18.06899872],
       [22.        , 20.43899524],
       [21.        , 21.22899408],
       [20.        , 20.43899524],
       [18.7       , 19.6489964 ],
       [18.        , 18.62199791],
       [16.8       , 18.06899872],
       [16.        , 17.12100012],
       [15.4       , 16.48900104],
       [15.1       , 16.01500174]])

In [ ]:
def rsquare(y,ycap):
  rss=((y-ycap)**2).sum()
  tss=((y-y.mean())**2).sum()
  r=1-(rss)/(tss)
  return r

In [ ]:
accuarcy=rsquare(Y,ycap)*100
accuarcy

np.float64(85.05854048089188)

In [ ]:
tmpr[-1]

15.1

In [ ]:
p=np.array([1,tmpr[-1]])
p

array([ 1. , 15.1])

In [ ]:
tommorrow=p.dot(w)
tommorrow

array([15.77800209])

In [ ]:
print("tommorrow temparature is ", round(tommorrow[0],2))

tommorrow temparature is  15.78


In [ ]:
#non linear polynomal degree2
p=np.array(past)
p2=p**2
X2=np.c_[ones,p,p2]
X2.shape

(17, 3)

In [ ]:
Y.shape

(17, 1)

In [ ]:
w2=weights(X2,Y)
w2

array([[5.41988955],
       [0.58901213],
       [0.00617348]])

In [ ]:
ycap=X2.dot(w2)
ycap

array([[11.92735843],
       [13.37701562],
       [14.12036464],
       [15.25853871],
       [16.42449342],
       [17.21723025],
       [17.94125004],
       [18.02231403],
       [20.51164708],
       [21.36611867],
       [20.51164708],
       [19.66952245],
       [18.59321911],
       [18.02231403],
       [17.05769513],
       [16.42449342],
       [15.95477786]])

In [ ]:
np.c_[Y,ycap]

array([[12.        , 11.92735843],
       [13.        , 13.37701562],
       [14.5       , 14.12036464],
       [16.        , 15.25853871],
       [17.        , 16.42449342],
       [17.9       , 17.21723025],
       [18.        , 17.94125004],
       [21.        , 18.02231403],
       [22.        , 20.51164708],
       [21.        , 21.36611867],
       [20.        , 20.51164708],
       [18.7       , 19.66952245],
       [18.        , 18.59321911],
       [16.8       , 18.02231403],
       [16.        , 17.05769513],
       [15.4       , 16.42449342],
       [15.1       , 15.95477786]])

In [ ]:
accuarcy2=rsquare(Y,ycap)*100
accuarcy2

np.float64(85.13230683487866)

In [ ]:
wipro = [
    249.63, 250.33, 255.88, 256.93, 254.15,
    254.01, 251.28, 251.94, 253.91, 255.75,
    249.15, 242.52, 243.67, 244.97, 249.56,
    250.93, 250.36, 249.41, 250.65, 252.03
]

In [ ]:
len(wipro)

20

In [ ]:
past=wipro[:-1]
present=wipro[1:]
list(zip(past,present))

[(249.63, 250.33),
 (250.33, 255.88),
 (255.88, 256.93),
 (256.93, 254.15),
 (254.15, 254.01),
 (254.01, 251.28),
 (251.28, 251.94),
 (251.94, 253.91),
 (253.91, 255.75),
 (255.75, 249.15),
 (249.15, 242.52),
 (242.52, 243.67),
 (243.67, 244.97),
 (244.97, 249.56),
 (249.56, 250.93),
 (250.93, 250.36),
 (250.36, 249.41),
 (249.41, 250.65),
 (250.65, 252.03)]

In [ ]:
np.corrcoef(past,present)

array([[1.       , 0.6929666],
       [0.6929666, 1.       ]])

In [ ]:
ones=np.ones(len(past))
len(ones)

19

In [ ]:
X=np.c_[ones,past]
X.shape

(19, 2)

In [ ]:
X

array([[  1.  , 249.63],
       [  1.  , 250.33],
       [  1.  , 255.88],
       [  1.  , 256.93],
       [  1.  , 254.15],
       [  1.  , 254.01],
       [  1.  , 251.28],
       [  1.  , 251.94],
       [  1.  , 253.91],
       [  1.  , 255.75],
       [  1.  , 249.15],
       [  1.  , 242.52],
       [  1.  , 243.67],
       [  1.  , 244.97],
       [  1.  , 249.56],
       [  1.  , 250.93],
       [  1.  , 250.36],
       [  1.  , 249.41],
       [  1.  , 250.65]])

In [ ]:
Y=np.c_[present]
Y.shape

(19, 1)

In [ ]:
Y

array([[250.33],
       [255.88],
       [256.93],
       [254.15],
       [254.01],
       [251.28],
       [251.94],
       [253.91],
       [255.75],
       [249.15],
       [242.52],
       [243.67],
       [244.97],
       [249.56],
       [250.93],
       [250.36],
       [249.41],
       [250.65],
       [252.03]])

In [ ]:
w=weights(X,Y)
w.shape

(2, 1)

In [ ]:
w

array([[77.16335551],
       [ 0.69282381]])

In [ ]:
ycap=X.dot(w)
ycap

array([[250.11296351],
       [250.59794018],
       [254.44311233],
       [255.17057733],
       [253.24452714],
       [253.1475318 ],
       [251.2561228 ],
       [251.71338652],
       [253.07824942],
       [254.35304524],
       [249.78040808],
       [245.18698621],
       [245.9837336 ],
       [246.88440455],
       [250.06446584],
       [251.01363447],
       [250.61872489],
       [249.96054227],
       [250.8196438 ]])

In [ ]:
np.c_[Y,ycap]

array([[250.33      , 250.11296351],
       [255.88      , 250.59794018],
       [256.93      , 254.44311233],
       [254.15      , 255.17057733],
       [254.01      , 253.24452714],
       [251.28      , 253.1475318 ],
       [251.94      , 251.2561228 ],
       [253.91      , 251.71338652],
       [255.75      , 253.07824942],
       [249.15      , 254.35304524],
       [242.52      , 249.78040808],
       [243.67      , 245.18698621],
       [244.97      , 245.9837336 ],
       [249.56      , 246.88440455],
       [250.93      , 250.06446584],
       [250.36      , 251.01363447],
       [249.41      , 250.61872489],
       [250.65      , 249.96054227],
       [252.03      , 250.8196438 ]])

In [ ]:
accu=rsquare(Y,ycap)*100
accu

np.float64(48.02027135494238)

In [ ]:
wipro[-1]


252.03

In [ ]:
p=np.c_[1,wipro[-1]]
p.shape

(1, 2)

In [ ]:
p

array([[  1.  , 252.03]])

In [ ]:
future=p.dot(w)
future

array([[251.77574066]])

In [ ]:
print("Tommorrow's share: ",round(future[0][0],2))

Tommorrow's share:  251.78


In [ ]:
#polynomail degree 2 (non linear)
q=np.array(past)
q2=q**2
X2=np.c_[ones,q,q2]
X2.shape


(19, 3)

In [ ]:
X2

array([[1.00000000e+00, 2.49630000e+02, 6.23151369e+04],
       [1.00000000e+00, 2.50330000e+02, 6.26651089e+04],
       [1.00000000e+00, 2.55880000e+02, 6.54745744e+04],
       [1.00000000e+00, 2.56930000e+02, 6.60130249e+04],
       [1.00000000e+00, 2.54150000e+02, 6.45922225e+04],
       [1.00000000e+00, 2.54010000e+02, 6.45210801e+04],
       [1.00000000e+00, 2.51280000e+02, 6.31416384e+04],
       [1.00000000e+00, 2.51940000e+02, 6.34737636e+04],
       [1.00000000e+00, 2.53910000e+02, 6.44702881e+04],
       [1.00000000e+00, 2.55750000e+02, 6.54080625e+04],
       [1.00000000e+00, 2.49150000e+02, 6.20757225e+04],
       [1.00000000e+00, 2.42520000e+02, 5.88159504e+04],
       [1.00000000e+00, 2.43670000e+02, 5.93750689e+04],
       [1.00000000e+00, 2.44970000e+02, 6.00103009e+04],
       [1.00000000e+00, 2.49560000e+02, 6.22801936e+04],
       [1.00000000e+00, 2.50930000e+02, 6.29658649e+04],
       [1.00000000e+00, 2.50360000e+02, 6.26801296e+04],
       [1.00000000e+00, 2.49410

In [ ]:
w2=weights(X2,Y)
w2.shape

(3, 1)

In [ ]:
w2

array([[-1.57335229e+03],
       [ 1.39096943e+01],
       [-2.64525657e-02]])

In [ ]:
ycap2=X2.dot(w2)
ycap2

array([[250.52945383],
       [251.00858256],
       [253.88981548],
       [254.25159732],
       [253.16651586],
       [253.10105766],
       [251.61736428],
       [252.01219888],
       [253.05366694],
       [253.84096562],
       [250.18592569],
       [244.19398779],
       [245.40001744],
       [246.67910388],
       [250.48011517],
       [251.39863132],
       [251.02853733],
       [250.37351652],
       [251.21897871]])

In [ ]:
np.c_[Y,ycap2]

array([[250.33      , 250.52945383],
       [255.88      , 251.00858256],
       [256.93      , 253.88981548],
       [254.15      , 254.25159732],
       [254.01      , 253.16651586],
       [251.28      , 253.10105766],
       [251.94      , 251.61736428],
       [253.91      , 252.01219888],
       [255.75      , 253.05366694],
       [249.15      , 253.84096562],
       [242.52      , 250.18592569],
       [243.67      , 244.19398779],
       [244.97      , 245.40001744],
       [249.56      , 246.67910388],
       [250.93      , 250.48011517],
       [250.36      , 251.39863132],
       [249.41      , 251.02853733],
       [250.65      , 250.37351652],
       [252.03      , 251.21897871]])

In [ ]:
acc=rsquare(Y,ycap2)*100
acc

np.float64(49.558401012750174)