<a href="https://colab.research.google.com/github/rakshithasetty41/statistics/blob/main/linear_regreesion_with_numpy_using_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pwd


/content


In [ ]:
infile=open('/content/diabietics_scores.txt.txt')

In [ ]:
header=infile.readline()
header

'  Age,BMI,Blood Pressure,Glucose Level,Insulin Level,Diabetic Status,diabetic_score\n'

In [ ]:
data=infile.readlines()
data

['  45,25.3,120,140,85,Yes,73.15\n',
 '  50,28.1,130,155,90,Yes,80.05\n',
 '  38,23.5,115,110,75,No,64.25\n',
 '  60,31.2,135,160,95,Yes,84.1\n',
 '  55,29.8,128,150,92,Yes,79.7\n',
 '  32,22.7,110,105,70,No,61.35\n',
 '  42,26.5,118,135,80,No,71.85\n',
 '  48,27.3,125,145,88,Yes,76.45\n',
 '  35,24.1,113,120,78,No,66.45\n',
 '  58,30.5,132,158,93,Yes,82.55\n',
 '  41,25.8,121,138,82,No,72.9\n',
 '  47,27.0,126,144,87,Yes,76.2\n',
 '  36,24.9,114,122,76,No,67.25\n',
 '  53,29.1,130,148,89,Yes,79.05000000000001\n',
 '  40,26.0,119,132,81,No,71.3\n',
 '  61,31.5,136,162,96,Yes,84.94999999999999\n',
 '  39,23.8,117,128,77,No,68.60000000000001\n',
 '  49,27.5,129,146,90,Yes,77.75\n',
 '  37,24.5,116,124,79,No,68.15\n',
 '  54,30.0,133,150,91,Yes,80.69999999999999']

In [ ]:
datawords=[line.strip().split(',')for line in data]
datawords

[['45', '25.3', '120', '140', '85', 'Yes', '73.15'],
 ['50', '28.1', '130', '155', '90', 'Yes', '80.05'],
 ['38', '23.5', '115', '110', '75', 'No', '64.25'],
 ['60', '31.2', '135', '160', '95', 'Yes', '84.1'],
 ['55', '29.8', '128', '150', '92', 'Yes', '79.7'],
 ['32', '22.7', '110', '105', '70', 'No', '61.35'],
 ['42', '26.5', '118', '135', '80', 'No', '71.85'],
 ['48', '27.3', '125', '145', '88', 'Yes', '76.45'],
 ['35', '24.1', '113', '120', '78', 'No', '66.45'],
 ['58', '30.5', '132', '158', '93', 'Yes', '82.55'],
 ['41', '25.8', '121', '138', '82', 'No', '72.9'],
 ['47', '27.0', '126', '144', '87', 'Yes', '76.2'],
 ['36', '24.9', '114', '122', '76', 'No', '67.25'],
 ['53', '29.1', '130', '148', '89', 'Yes', '79.05000000000001'],
 ['40', '26.0', '119', '132', '81', 'No', '71.3'],
 ['61', '31.5', '136', '162', '96', 'Yes', '84.94999999999999'],
 ['39', '23.8', '117', '128', '77', 'No', '68.60000000000001'],
 ['49', '27.5', '129', '146', '90', 'Yes', '77.75'],
 ['37', '24.5', '116', 

In [ ]:
inputs=[l[:5] for l in datawords]
inputs

[['45', '25.3', '120', '140', '85'],
 ['50', '28.1', '130', '155', '90'],
 ['38', '23.5', '115', '110', '75'],
 ['60', '31.2', '135', '160', '95'],
 ['55', '29.8', '128', '150', '92'],
 ['32', '22.7', '110', '105', '70'],
 ['42', '26.5', '118', '135', '80'],
 ['48', '27.3', '125', '145', '88'],
 ['35', '24.1', '113', '120', '78'],
 ['58', '30.5', '132', '158', '93'],
 ['41', '25.8', '121', '138', '82'],
 ['47', '27.0', '126', '144', '87'],
 ['36', '24.9', '114', '122', '76'],
 ['53', '29.1', '130', '148', '89'],
 ['40', '26.0', '119', '132', '81'],
 ['61', '31.5', '136', '162', '96'],
 ['39', '23.8', '117', '128', '77'],
 ['49', '27.5', '129', '146', '90'],
 ['37', '24.5', '116', '124', '79'],
 ['54', '30.0', '133', '150', '91']]

In [ ]:
def tofloat(xlist):
  return [float(x) for x in xlist]

In [ ]:
inputs =[tofloat(x) for x in inputs]
inputs

[[45.0, 25.3, 120.0, 140.0, 85.0],
 [50.0, 28.1, 130.0, 155.0, 90.0],
 [38.0, 23.5, 115.0, 110.0, 75.0],
 [60.0, 31.2, 135.0, 160.0, 95.0],
 [55.0, 29.8, 128.0, 150.0, 92.0],
 [32.0, 22.7, 110.0, 105.0, 70.0],
 [42.0, 26.5, 118.0, 135.0, 80.0],
 [48.0, 27.3, 125.0, 145.0, 88.0],
 [35.0, 24.1, 113.0, 120.0, 78.0],
 [58.0, 30.5, 132.0, 158.0, 93.0],
 [41.0, 25.8, 121.0, 138.0, 82.0],
 [47.0, 27.0, 126.0, 144.0, 87.0],
 [36.0, 24.9, 114.0, 122.0, 76.0],
 [53.0, 29.1, 130.0, 148.0, 89.0],
 [40.0, 26.0, 119.0, 132.0, 81.0],
 [61.0, 31.5, 136.0, 162.0, 96.0],
 [39.0, 23.8, 117.0, 128.0, 77.0],
 [49.0, 27.5, 129.0, 146.0, 90.0],
 [37.0, 24.5, 116.0, 124.0, 79.0],
 [54.0, 30.0, 133.0, 150.0, 91.0]]

In [ ]:
dscore = [float(x[-1]) for x in datawords]
dscore

[73.15,
 80.05,
 64.25,
 84.1,
 79.7,
 61.35,
 71.85,
 76.45,
 66.45,
 82.55,
 72.9,
 76.2,
 67.25,
 79.05000000000001,
 71.3,
 84.94999999999999,
 68.60000000000001,
 77.75,
 68.15,
 80.69999999999999]

In [ ]:
import numpy as np


In [ ]:
ones=np.ones(len(inputs))
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
#input variable
X=np.c_[ones,inputs]
X


array([[  1. ,  45. ,  25.3, 120. , 140. ,  85. ],
       [  1. ,  50. ,  28.1, 130. , 155. ,  90. ],
       [  1. ,  38. ,  23.5, 115. , 110. ,  75. ],
       [  1. ,  60. ,  31.2, 135. , 160. ,  95. ],
       [  1. ,  55. ,  29.8, 128. , 150. ,  92. ],
       [  1. ,  32. ,  22.7, 110. , 105. ,  70. ],
       [  1. ,  42. ,  26.5, 118. , 135. ,  80. ],
       [  1. ,  48. ,  27.3, 125. , 145. ,  88. ],
       [  1. ,  35. ,  24.1, 113. , 120. ,  78. ],
       [  1. ,  58. ,  30.5, 132. , 158. ,  93. ],
       [  1. ,  41. ,  25.8, 121. , 138. ,  82. ],
       [  1. ,  47. ,  27. , 126. , 144. ,  87. ],
       [  1. ,  36. ,  24.9, 114. , 122. ,  76. ],
       [  1. ,  53. ,  29.1, 130. , 148. ,  89. ],
       [  1. ,  40. ,  26. , 119. , 132. ,  81. ],
       [  1. ,  61. ,  31.5, 136. , 162. ,  96. ],
       [  1. ,  39. ,  23.8, 117. , 128. ,  77. ],
       [  1. ,  49. ,  27.5, 129. , 146. ,  90. ],
       [  1. ,  37. ,  24.5, 116. , 124. ,  79. ],
       [  1. ,  54. ,  30. , 13

In [ ]:
X.shape

(20, 6)

In [ ]:
Y=np.c_[dscore]
Y.shape

(20, 1)

In [ ]:
Y

array([[73.15],
       [80.05],
       [64.25],
       [84.1 ],
       [79.7 ],
       [61.35],
       [71.85],
       [76.45],
       [66.45],
       [82.55],
       [72.9 ],
       [76.2 ],
       [67.25],
       [79.05],
       [71.3 ],
       [84.95],
       [68.6 ],
       [77.75],
       [68.15],
       [80.7 ]])

In [ ]:
def Weights(x,y):
  from numpy.linalg import inv
  left=inv(x.T.dot(x))
  rgt=x.T.dot(y)
  return left.dot(rgt)

In [ ]:
w = Weights(X, Y)
w.shape

(6, 1)

In [ ]:
w

array([[2.21916707e-10],
       [3.41060513e-13],
       [5.00000000e-01],
       [2.00000000e-01],
       [2.00000000e-01],
       [1.00000000e-01]])

In [ ]:
Y=X.dot(w)
Y.shape

(20, 1)

In [ ]:
Y

array([[73.15],
       [80.05],
       [64.25],
       [84.1 ],
       [79.7 ],
       [61.35],
       [71.85],
       [76.45],
       [66.45],
       [82.55],
       [72.9 ],
       [76.2 ],
       [67.25],
       [79.05],
       [71.3 ],
       [84.95],
       [68.6 ],
       [77.75],
       [68.15],
       [80.7 ]])

In [ ]:
Ycap=X.dot(w)
Ycap.shape

(20, 1)

In [ ]:
Ycap

array([[73.15],
       [80.05],
       [64.25],
       [84.1 ],
       [79.7 ],
       [61.35],
       [71.85],
       [76.45],
       [66.45],
       [82.55],
       [72.9 ],
       [76.2 ],
       [67.25],
       [79.05],
       [71.3 ],
       [84.95],
       [68.6 ],
       [77.75],
       [68.15],
       [80.7 ]])

In [ ]:
np.c_[Y,Ycap]

array([[73.15, 73.15],
       [80.05, 80.05],
       [64.25, 64.25],
       [84.1 , 84.1 ],
       [79.7 , 79.7 ],
       [61.35, 61.35],
       [71.85, 71.85],
       [76.45, 76.45],
       [66.45, 66.45],
       [82.55, 82.55],
       [72.9 , 72.9 ],
       [76.2 , 76.2 ],
       [67.25, 67.25],
       [79.05, 79.05],
       [71.3 , 71.3 ],
       [84.95, 84.95],
       [68.6 , 68.6 ],
       [77.75, 77.75],
       [68.15, 68.15],
       [80.7 , 80.7 ]])

In [ ]:
dy=Y.mean()
dy

np.float64(74.33750000011722)

In [ ]:
rss=((Y-Ycap)**2).sum()
tss=((Y-dy)**2).sum()
rs=1-(rss/tss)
rs

np.float64(1.0)

In [ ]:
def square(Y,Ycap):
  rss=((Y-Ycap)**2).sum()
  tss=((Y-Y.mean())**2).sum()
  rs=1-(rss/tss)
  return rs

In [ ]:
rsquare=square(Y,Ycap)*100
rsquare

np.float64(100.0)

In [ ]:
# prediction of diabetic scores for the new patients.

In [ ]:
inpats=open('/content/newpat_diabieticscores.txt')
newpats=inpats.readlines()
newpats


[' 49,27.3,125,145,88\n',
 ' 37,25.1,113,120,78\n',
 ' 57,31.5,134,158,93\n',
 ' 42,26.8,121,138,82']

In [ ]:
newdata=[line.strip().split(',') for line in newpats]
newdata

[['49', '27.3', '125', '145', '88'],
 ['37', '25.1', '113', '120', '78'],
 ['57', '31.5', '134', '158', '93'],
 ['42', '26.8', '121', '138', '82']]

In [ ]:
newdata=[tofloat(x) for x in newdata]
newdata

[[49.0, 27.3, 125.0, 145.0, 88.0],
 [37.0, 25.1, 113.0, 120.0, 78.0],
 [57.0, 31.5, 134.0, 158.0, 93.0],
 [42.0, 26.8, 121.0, 138.0, 82.0]]

In [ ]:
newones=np.ones(len(newdata))
newinputs=np.c_[newones,newdata]
newinputs


array([[  1. ,  49. ,  27.3, 125. , 145. ,  88. ],
       [  1. ,  37. ,  25.1, 113. , 120. ,  78. ],
       [  1. ,  57. ,  31.5, 134. , 158. ,  93. ],
       [  1. ,  42. ,  26.8, 121. , 138. ,  82. ]])

In [ ]:
newinputs.shape

(4, 6)

In [ ]:
y

array([[76.45],
       [66.95],
       [83.45],
       [73.4 ]])

In [ ]:
y=newinputs.dot(w)
y.shape

(4, 1)

In [ ]:
np.c_[newinputs,y]

array([[  1.  ,  49.  ,  27.3 , 125.  , 145.  ,  88.  ,  76.45],
       [  1.  ,  37.  ,  25.1 , 113.  , 120.  ,  78.  ,  66.95],
       [  1.  ,  57.  ,  31.5 , 134.  , 158.  ,  93.  ,  83.45],
       [  1.  ,  42.  ,  26.8 , 121.  , 138.  ,  82.  ,  73.4 ]])