<a href="https://colab.research.google.com/github/rakshithasetty41/statistics/blob/main/non_linear_poly_degree_2_and_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
infile=open('/content/diabietics_scores.txt')
header=infile.readline()
data=infile.readlines()
len(data)


20

In [ ]:
data[:3]

['  45,25.3,120,140,85,Yes,73.15\n',
 '  50,28.1,130,155,90,Yes,80.05\n',
 '  38,23.5,115,110,75,No,64.25\n']

In [ ]:
age=[]
bmi=[]
bp=[]
gl=[]
il=[]
dscore=[]


In [ ]:
 for line in data:
   w = line.strip().split(',')
   # [age, bmi, bp, gl, il, dstat, dscore]
   age.append(float(w[0]))
   bmi.append(float(w[1]))
   bp.append(float(w[2]))
   gl.append(float(w[3]))
   il.append(float(w[-3]))
   dscore.append(float(w[-1]))

In [ ]:
age

[45.0,
 50.0,
 38.0,
 60.0,
 55.0,
 32.0,
 42.0,
 48.0,
 35.0,
 58.0,
 41.0,
 47.0,
 36.0,
 53.0,
 40.0,
 61.0,
 39.0,
 49.0,
 37.0,
 54.0]

In [ ]:
import numpy as np


In [ ]:
age=np.array(age)
bmi=np.array(bmi)
bp=np.array(bp)
gl=np.array(gl)
il=np.array(il)
dscore=np.array(dscore)


In [ ]:
ones = np.ones(len(age))
X_linear = np.c_[ones, age, bmi, bp, gl, il]
Y = np.c_[dscore]


In [ ]:
X_linear.shape

(20, 6)

In [ ]:
def weights(x,y):
  from numpy.linalg import inv
  left=inv(x.T.dot(x))
  rgt=x.T.dot(y)
  return left.dot(rgt)

In [ ]:
weights_linear=weights(X_linear,Y)
weights_linear

array([[2.21916707e-10],
       [3.41060513e-13],
       [5.00000000e-01],
       [2.00000000e-01],
       [2.00000000e-01],
       [1.00000000e-01]])

In [ ]:
weights_linear.shape

(6, 1)

In [ ]:
def predict(x,w):
  return x.dot(w)

In [ ]:
ycap_predict_linear=predict(X_linear,weights_linear)
ycap_predict_linear

array([[73.15],
       [80.05],
       [64.25],
       [84.1 ],
       [79.7 ],
       [61.35],
       [71.85],
       [76.45],
       [66.45],
       [82.55],
       [72.9 ],
       [76.2 ],
       [67.25],
       [79.05],
       [71.3 ],
       [84.95],
       [68.6 ],
       [77.75],
       [68.15],
       [80.7 ]])

In [ ]:
ycap_predict_linear.shape

(20, 1)

In [ ]:
def square(y,ycap):
  rss=((y-ycap)**2).sum()
  tss=((y-y.mean()**2)).sum()
  return 1-(rss/tss)

In [ ]:
accurancy_linear=square(Y,ycap_predict_linear)*100
accurancy_linear


np.float64(100.0)

In [ ]:
#non linear poly degree 2
age2=age**2
bmi2=bmi**2
bp2=bp**2
gl2=gl**2
il2=il**2
X_poly2 = np.c_[ones, age, age2, bmi, bmi2, bp, bp2, gl, gl2, il, il2]
X_poly2.shape

(20, 11)

In [ ]:
w_poly2=weights(X_poly2,Y)
w_poly2

array([[ 5.96046448e-08],
       [-5.47515810e-09],
       [ 6.36646291e-11],
       [ 5.00000039e-01],
       [-7.95353117e-10],
       [ 1.99999993e-01],
       [ 2.88764568e-11],
       [ 2.00000000e-01],
       [-2.84217094e-13],
       [ 9.99999999e-02],
       [ 0.00000000e+00]])

In [ ]:
w_poly2.shape

(11, 1)

In [ ]:
ycap_poly2=predict(X_poly2,w_poly2)
ycap_poly2

array([[73.14999999],
       [80.04999998],
       [64.24999999],
       [84.09999998],
       [79.69999998],
       [61.35      ],
       [71.84999999],
       [76.44999999],
       [66.45      ],
       [82.54999998],
       [72.89999999],
       [76.19999999],
       [67.25      ],
       [79.04999998],
       [71.29999999],
       [84.94999998],
       [68.59999999],
       [77.74999999],
       [68.14999999],
       [80.69999998]])

In [ ]:
ycap_poly2.shape

(20, 1)

In [ ]:
accuaracy_poly2=square(Y,ycap_poly2)*100
accuaracy_poly2

np.float64(100.0)

In [ ]:
# experiment with poly degree 3
age3 = age**3
bmi3 = bmi**3
bp3 = bp**3
gl3 = gl**3
il3 = il**3
X_poly3 = np.c_[ones, age, age2, age3, bmi, bmi2, bmi3, bp, bp2, bp3,
                gl, gl2, gl3, il, il2, il3]
X_poly3.shape

(20, 16)

In [ ]:
w_poly3=weights(X_poly3,Y)
w_poly3

array([[ 3.27148438e-02],
       [-1.15633011e-04],
       [ 2.53692269e-06],
       [-1.81898940e-08],
       [ 4.98292923e-01],
       [ 6.48498535e-05],
       [-8.14441592e-07],
       [ 1.99634552e-01],
       [ 2.86102295e-06],
       [-7.50878826e-09],
       [ 1.99989200e-01],
       [ 8.10250640e-08],
       [-2.00088834e-10],
       [ 1.00000381e-01],
       [-1.49011612e-08],
       [ 5.82076609e-11]])

In [ ]:
w_poly3.shape

(16, 1)

In [ ]:
ycap_pol3=predict(X_poly3,w_poly3)
ycap_pol3

array([[73.14997977],
       [80.0499979 ],
       [64.24999926],
       [84.09992224],
       [79.70000079],
       [61.35008178],
       [71.85000068],
       [76.44999788],
       [66.4500143 ],
       [82.54996796],
       [72.89997871],
       [76.19999034],
       [67.25000869],
       [79.05000527],
       [71.29998745],
       [84.94989601],
       [68.59998422],
       [77.7499923 ],
       [68.14999001],
       [80.6999882 ]])

In [ ]:
ycap_pol3.shape

(20, 1)

In [ ]:
accuarcy_pol3=square(Y,ycap_pol3)*100
accuarcy_pol3

np.float64(100.00000000002436)