<a href="https://colab.research.google.com/github/rakshithasetty41/statistics/blob/main/numpy_with_matrix_dimensions_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
t=[20,40,90,50,70]
on=[100,120,130,200,150]
cr=[40,50,40,60,70]
price=np.array([t,on,cr])
print(price)


[[ 20  40  90  50  70]
 [100 120 130 200 150]
 [ 40  50  40  60  70]]


In [ ]:
price


array([[ 20,  40,  90,  50,  70],
       [100, 120, 130, 200, 150],
       [ 40,  50,  40,  60,  70]])

In [ ]:
len(price)

3

In [ ]:
price.size

15

In [ ]:
price[-1,0]

np.int64(40)

In [ ]:
price[0,-1]


np.int64(70)

In [ ]:
price[1].mean()

np.float64(140.0)

In [ ]:
price[:,-1].mean()

np.float64(96.66666666666667)

In [ ]:
price

array([[ 20,  40,  90,  50,  70],
       [100, 120, 130, 200, 150],
       [ 40,  50,  40,  60,  70]])

In [ ]:
price[:-1,-2:]

array([[ 50,  70],
       [200, 150]])

In [ ]:
price[0:,-1]

array([ 70, 150,  70])

In [ ]:
price[:,2:]

array([[ 90,  50,  70],
       [130, 200, 150],
       [ 40,  60,  70]])

In [ ]:
price[1:,1:3]

array([[120, 130],
       [ 50,  40]])

In [ ]:
price[2,1:4]

array([50, 40, 60])

In [ ]:
hyd=price.copy()
delhi=price*0.2
pune=price*0.8

In [ ]:
hyd

array([[ 20,  40,  90,  50,  70],
       [100, 120, 130, 200, 150],
       [ 40,  50,  40,  60,  70]])

In [ ]:
delhi

array([[ 4.,  8., 18., 10., 14.],
       [20., 24., 26., 40., 30.],
       [ 8., 10.,  8., 12., 14.]])

In [ ]:
pune

array([[ 16.,  32.,  72.,  40.,  56.],
       [ 80.,  96., 104., 160., 120.],
       [ 32.,  40.,  32.,  48.,  56.]])

In [ ]:
price=np.array([hyd,delhi,pune])

In [ ]:
price

array([[[ 20.,  40.,  90.,  50.,  70.],
        [100., 120., 130., 200., 150.],
        [ 40.,  50.,  40.,  60.,  70.]],

       [[  4.,   8.,  18.,  10.,  14.],
        [ 20.,  24.,  26.,  40.,  30.],
        [  8.,  10.,   8.,  12.,  14.]],

       [[ 16.,  32.,  72.,  40.,  56.],
        [ 80.,  96., 104., 160., 120.],
        [ 32.,  40.,  32.,  48.,  56.]]])

In [ ]:
price[-1,0,-1]

np.float64(56.0)

In [ ]:
price[1,-1,-2]

np.float64(12.0)

In [ ]:
price[1,2].mean()

np.float64(10.4)

In [ ]:
price[-1,:,-1].mean()

np.float64(77.33333333333333)

In [ ]:
price[:,0,-2]

array([50., 10., 40.])

In [ ]:
price

array([[[ 20.,  40.,  90.,  50.,  70.],
        [100., 120., 130., 200., 150.],
        [ 40.,  50.,  40.,  60.,  70.]],

       [[  4.,   8.,  18.,  10.,  14.],
        [ 20.,  24.,  26.,  40.,  30.],
        [  8.,  10.,   8.,  12.,  14.]],

       [[ 16.,  32.,  72.,  40.,  56.],
        [ 80.,  96., 104., 160., 120.],
        [ 32.,  40.,  32.,  48.,  56.]]])

In [ ]:
price[1,0,2]

np.float64(18.0)

In [ ]:
price[:,0,:]

array([[20., 40., 90., 50., 70.],
       [ 4.,  8., 18., 10., 14.],
       [16., 32., 72., 40., 56.]])

In [ ]:
price[:,0:,2]

array([[ 90., 130.,  40.],
       [ 18.,  26.,   8.],
       [ 72., 104.,  32.]])

In [ ]:
price[:,:,0:3]

array([[[ 20.,  40.,  90.],
        [100., 120., 130.],
        [ 40.,  50.,  40.]],

       [[  4.,   8.,  18.],
        [ 20.,  24.,  26.],
        [  8.,  10.,   8.]],

       [[ 16.,  32.,  72.],
        [ 80.,  96., 104.],
        [ 32.,  40.,  32.]]])

In [ ]:
domestic=price.copy()
export=domestic*3
price=np.array([domestic,export])
price

array([[[[ 20.,  40.,  90.,  50.,  70.],
         [100., 120., 130., 200., 150.],
         [ 40.,  50.,  40.,  60.,  70.]],

        [[  4.,   8.,  18.,  10.,  14.],
         [ 20.,  24.,  26.,  40.,  30.],
         [  8.,  10.,   8.,  12.,  14.]],

        [[ 16.,  32.,  72.,  40.,  56.],
         [ 80.,  96., 104., 160., 120.],
         [ 32.,  40.,  32.,  48.,  56.]]],


       [[[ 60., 120., 270., 150., 210.],
         [300., 360., 390., 600., 450.],
         [120., 150., 120., 180., 210.]],

        [[ 12.,  24.,  54.,  30.,  42.],
         [ 60.,  72.,  78., 120.,  90.],
         [ 24.,  30.,  24.,  36.,  42.]],

        [[ 48.,  96., 216., 120., 168.],
         [240., 288., 312., 480., 360.],
         [ 96., 120.,  96., 144., 168.]]]])

In [ ]:
price.size


90

In [ ]:
price.ndim

4

In [ ]:
len(price)

2

In [ ]:
price.shape

(2, 3, 3, 5)

In [ ]:
price[-1,-1,1].mean()

np.float64(336.0)

In [ ]:
price[:,1,:,3:]

array([[[ 10.,  14.],
        [ 40.,  30.],
        [ 12.,  14.]],

       [[ 30.,  42.],
        [120.,  90.],
        [ 36.,  42.]]])

In [ ]:
price

array([[[[ 20.,  40.,  90.,  50.,  70.],
         [100., 120., 130., 200., 150.],
         [ 40.,  50.,  40.,  60.,  70.]],

        [[  4.,   8.,  18.,  10.,  14.],
         [ 20.,  24.,  26.,  40.,  30.],
         [  8.,  10.,   8.,  12.,  14.]],

        [[ 16.,  32.,  72.,  40.,  56.],
         [ 80.,  96., 104., 160., 120.],
         [ 32.,  40.,  32.,  48.,  56.]]],


       [[[ 60., 120., 270., 150., 210.],
         [300., 360., 390., 600., 450.],
         [120., 150., 120., 180., 210.]],

        [[ 12.,  24.,  54.,  30.,  42.],
         [ 60.,  72.,  78., 120.,  90.],
         [ 24.,  30.,  24.,  36.,  42.]],

        [[ 48.,  96., 216., 120., 168.],
         [240., 288., 312., 480., 360.],
         [ 96., 120.,  96., 144., 168.]]]])

In [ ]:
price[1,:,1:,:]

array([[[300., 360., 390., 600., 450.],
        [120., 150., 120., 180., 210.]],

       [[ 60.,  72.,  78., 120.,  90.],
        [ 24.,  30.,  24.,  36.,  42.]],

       [[240., 288., 312., 480., 360.],
        [ 96., 120.,  96., 144., 168.]]])

In [ ]:
price[1,1,:,-3]

array([54., 78., 24.])

In [ ]:
price[1,0,0,0]

np.float64(60.0)

In [ ]:
price[1,:,1,-1]

array([450.,  90., 360.])

In [ ]:
price[1,:,:,-1]

array([[210., 450., 210.],
       [ 42.,  90.,  42.],
       [168., 360., 168.]])