<a href="https://colab.research.google.com/github/rakshithasetty41/statistics/blob/main/var%2Cstd%2Ccorrelation%2Ccovariance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A=np.array([[10,20],[20,40],[40,50]])

In [ ]:
A.shape

(3, 2)

In [ ]:
B=np.array([[10,100],[1,3],[4,6]])

In [ ]:
B.shape

(3, 2)

In [ ]:
c=A+B
c

array([[ 20, 120],
       [ 21,  43],
       [ 44,  56]])

In [ ]:
D=A*B
D

array([[ 100, 2000],
       [  20,  120],
       [ 160,  300]])

In [ ]:
At=np.transpose(A)
At

array([[10, 20, 40],
       [20, 40, 50]])

In [ ]:
c=np.array([[2,5],[3,6]])
c

array([[2, 5],
       [3, 6]])

In [ ]:
c.shape

(2, 2)

In [ ]:
A

array([[10, 20],
       [20, 40],
       [40, 50]])

In [ ]:
A.shape


(3, 2)

In [ ]:
m=A.dot(c)
m

array([[ 80, 170],
       [160, 340],
       [230, 500]])

In [ ]:
m=A.dot(At)
m

array([[ 500, 1000, 1400],
       [1000, 2000, 2800],
       [1400, 2800, 4100]])

In [ ]:
m=At.dot(A)
m

array([[2100, 3000],
       [3000, 4500]])

In [ ]:
from numpy.linalg import inv
M=inv(m)
M

array([[ 0.01      , -0.00666667],
       [-0.00666667,  0.00466667]])

In [ ]:
a=A.ravel()#convert of 2d or nd into a single dimension
a

array([10, 20, 20, 40, 40, 50])

In [ ]:
#python methods
sum(a)

np.int64(180)

In [ ]:
len(a)

6

In [ ]:
max(a)

np.int64(50)

In [ ]:
min(a)

np.int64(10)

In [ ]:
sum(a)/len(a)

np.float64(30.0)

In [ ]:
#numpy methods
a.sum()

np.int64(180)

In [ ]:
a.size

6

In [ ]:
a.mean()

np.float64(30.0)

In [ ]:
a.max()

np.int64(50)

In [ ]:
A.max(axis=0)#in columns it will give a max

array([40, 50])

In [ ]:
A.max(axis=1)#in rows it willl give a max

array([20, 40, 50])

In [ ]:
a.min()

np.int64(10)

In [ ]:
  A.min(axis=0)

array([10, 20])

In [ ]:
A.min(axis=1)

array([10, 20, 40])

In [ ]:
A.mean(axis=0)

array([23.33333333, 36.66666667])

In [ ]:
A.mean(axis=1)


array([15., 30., 45.])

In [ ]:
A.sum(axis=0)

array([ 70, 110])

In [ ]:
A.sum(axis=1)

array([30, 60, 90])

In [ ]:
#artithemetic mean
def amean(x):
  return sum(x)/len(x)

In [ ]:
amean(a)

np.float64(30.0)

In [ ]:
#gemoetric mean
def gmean(x):

  return x.prod()**(1/x.size)

In [ ]:
gmean(a)

np.float64(26.153209720236607)

In [ ]:
def hmean(x):
  return x.size/sum(1/x)

In [ ]:
hmean(a)

np.float64(22.22222222222222)

In [ ]:
def mean(x):
  am=amean(x)
  gm=gmean(x)
  hm=hmean(x)
  return (int(am),int(gm),int(hm))

In [ ]:
mean(a)

(30, 26, 22)

In [ ]:
#variance
def varpop(x):
  mx=x.mean()
  dx=sum((x-mx)**2)
  den=x.size
  return dx/den

In [ ]:
varpop(a)

np.float64(200.0)

In [ ]:
def varsamp(x):
  mx=x.mean()
  dx=sum((x-mx)**2)
  den=x.size-1
  return dx/den

In [ ]:
varsamp(a)

np.float64(240.0)

In [ ]:
def sdpop(x):
  return varpop(x)**0.5

In [ ]:
sdpop(a)

np.float64(14.142135623730951)

In [ ]:
def sdsamp(x):
  return varsamp(x)**0.5

In [ ]:
sdsamp(a)

np.float64(15.491933384829668)

In [ ]:
def covar(x,y):
  mx=x.mean()
  my=y.mean()
  dx=x-mx
  dy=y-my
  num=sum(dx*dy)
  den=x.size-1
  return num/den

In [ ]:
b=B.ravel()
b

array([ 10, 100,   1,   3,   4,   6])

In [ ]:
covar(a,b)

np.float64(-203.99999999999997)

In [ ]:
def corr(x,y):
  mx=x.mean()
  my=y.mean()
  dx=x-mx
  dy=y-my
  num=sum(dx*dy)
  left=sum(dx**2)
  rgt=sum(dy**2)
  den=(left*rgt)**0.5
  return num/den

In [ ]:
corr(a,b)

np.float64(-0.33777056587498305)

In [ ]:
age=[20,25,30,26,22,30,35,40,32]
exp=[0,3,6,4,1,5,8,20,9]
age=np.array(age)
exp=np.array(exp)
income=5+2*age+3*exp
income


array([ 45,  64,  83,  69,  52,  80,  99, 145,  96])

In [ ]:
income=np.array(income)
income

array([ 45,  64,  83,  69,  52,  80,  99, 145,  96])

In [ ]:
age

array([20, 25, 30, 26, 22, 30, 35, 40, 32])

In [ ]:
exp

array([ 0,  3,  6,  4,  1,  5,  8, 20,  9])

In [ ]:
np.c_[age,exp,income]

array([[ 20,   0,  45],
       [ 25,   3,  64],
       [ 30,   6,  83],
       [ 26,   4,  69],
       [ 22,   1,  52],
       [ 30,   5,  80],
       [ 35,   8,  99],
       [ 40,  20, 145],
       [ 32,   9,  96]])

In [ ]:
#step1:give me the input variables
ones=np.ones(len(age))
x=np.c_[ones,age,exp]

In [ ]:
x

array([[ 1., 20.,  0.],
       [ 1., 25.,  3.],
       [ 1., 30.,  6.],
       [ 1., 26.,  4.],
       [ 1., 22.,  1.],
       [ 1., 30.,  5.],
       [ 1., 35.,  8.],
       [ 1., 40., 20.],
       [ 1., 32.,  9.]])

In [ ]:
#estimeate the target variabale
y=np.c_[income]
y

array([[ 45],
       [ 64],
       [ 83],
       [ 69],
       [ 52],
       [ 80],
       [ 99],
       [145],
       [ 96]])

In [ ]:
from numpy.linalg import inv
left=inv(x.T.dot(x))
left

array([[11.98235016, -0.5165406 ,  0.49034649],
       [-0.5165406 ,  0.02273719, -0.02255009],
       [ 0.49034649, -0.02255009,  0.02589118]])

In [ ]:
w.shape

(3, 1)

In [ ]:
rgt=(x.T.dot(y))
rgt

array([[  733.],
       [22665.],
       [ 5974.]])

In [ ]:

w=left.dot(rgt)
w

array([[5.],
       [2.],
       [3.]])

In [ ]:
def weights(x,y):
  from numpy.linalg import inv
  left=inv(x.T.dot(x))
  rgt=(x.T.dot(y))
  w=left.dot(rgt)
  return w


In [ ]:
weights(x,y)

array([[5.],
       [2.],
       [3.]])

In [ ]:
#newdata
#firstone ravi,age=25,exp=5
#second one latha,age=24,exp=2
newage=[25,24]
newexp=[5,2]
newage=np.array(newage)
newexp=np.array(newexp)
newones=np.ones(len(newage))
newones

array([1., 1.])

In [ ]:
x=np.c_[newones,newage,newexp]
x

array([[ 1., 25.,  5.],
       [ 1., 24.,  2.]])

In [ ]:
#predicative equation y=x.w
w

array([[5.],
       [2.],
       [3.]])

In [ ]:
predictive_equation=x.dot(w)
predictive_equation


array([[70.],
       [59.]])

In [ ]:
pwd

'/content'

In [ ]:
infile = open('/content/diabietics_scores.txt')

In [ ]:
header=infile.readline()
header

'  Age,BMI,Blood Pressure,Glucose Level,Insulin Level,Diabetic Status,diabetic_score\n'

In [ ]:
data=infile.readlines()
data

['  45,25.3,120,140,85,Yes,73.15\n',
 '  50,28.1,130,155,90,Yes,80.05\n',
 '  38,23.5,115,110,75,No,64.25\n',
 '  60,31.2,135,160,95,Yes,84.1\n',
 '  55,29.8,128,150,92,Yes,79.7\n',
 '  32,22.7,110,105,70,No,61.35\n',
 '  42,26.5,118,135,80,No,71.85\n',
 '  48,27.3,125,145,88,Yes,76.45\n',
 '  35,24.1,113,120,78,No,66.45\n',
 '  58,30.5,132,158,93,Yes,82.55\n',
 '  41,25.8,121,138,82,No,72.9\n',
 '  47,27.0,126,144,87,Yes,76.2\n',
 '  36,24.9,114,122,76,No,67.25\n',
 '  53,29.1,130,148,89,Yes,79.05000000000001\n',
 '  40,26.0,119,132,81,No,71.3\n',
 '  61,31.5,136,162,96,Yes,84.94999999999999\n',
 '  39,23.8,117,128,77,No,68.60000000000001\n',
 '  49,27.5,129,146,90,Yes,77.75\n',
 '  37,24.5,116,124,79,No,68.15\n',
 '  54,30.0,133,150,91,Yes,80.69999999999999']

In [ ]:
datawords=[lines.strip().split(',')for lines in data]
datawords

[['45', '25.3', '120', '140', '85', 'Yes', '73.15'],
 ['50', '28.1', '130', '155', '90', 'Yes', '80.05'],
 ['38', '23.5', '115', '110', '75', 'No', '64.25'],
 ['60', '31.2', '135', '160', '95', 'Yes', '84.1'],
 ['55', '29.8', '128', '150', '92', 'Yes', '79.7'],
 ['32', '22.7', '110', '105', '70', 'No', '61.35'],
 ['42', '26.5', '118', '135', '80', 'No', '71.85'],
 ['48', '27.3', '125', '145', '88', 'Yes', '76.45'],
 ['35', '24.1', '113', '120', '78', 'No', '66.45'],
 ['58', '30.5', '132', '158', '93', 'Yes', '82.55'],
 ['41', '25.8', '121', '138', '82', 'No', '72.9'],
 ['47', '27.0', '126', '144', '87', 'Yes', '76.2'],
 ['36', '24.9', '114', '122', '76', 'No', '67.25'],
 ['53', '29.1', '130', '148', '89', 'Yes', '79.05000000000001'],
 ['40', '26.0', '119', '132', '81', 'No', '71.3'],
 ['61', '31.5', '136', '162', '96', 'Yes', '84.94999999999999'],
 ['39', '23.8', '117', '128', '77', 'No', '68.60000000000001'],
 ['49', '27.5', '129', '146', '90', 'Yes', '77.75'],
 ['37', '24.5', '116', 

In [ ]:

inputs=[l[:5]for l in datawords]
inputs

[['45', '25.3', '120', '140', '85'],
 ['50', '28.1', '130', '155', '90'],
 ['38', '23.5', '115', '110', '75'],
 ['60', '31.2', '135', '160', '95'],
 ['55', '29.8', '128', '150', '92'],
 ['32', '22.7', '110', '105', '70'],
 ['42', '26.5', '118', '135', '80'],
 ['48', '27.3', '125', '145', '88'],
 ['35', '24.1', '113', '120', '78'],
 ['58', '30.5', '132', '158', '93'],
 ['41', '25.8', '121', '138', '82'],
 ['47', '27.0', '126', '144', '87'],
 ['36', '24.9', '114', '122', '76'],
 ['53', '29.1', '130', '148', '89'],
 ['40', '26.0', '119', '132', '81'],
 ['61', '31.5', '136', '162', '96'],
 ['39', '23.8', '117', '128', '77'],
 ['49', '27.5', '129', '146', '90'],
 ['37', '24.5', '116', '124', '79'],
 ['54', '30.0', '133', '150', '91']]

In [ ]:
def tofloat(x):
  return [tofloat(x) for x in inputs]

In [ ]:
inputs=[tofloat(x) for x in inputs]
inputs